# Generated by Django 5.2 on 2025-04-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('creci', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Corretor',
                'verbose_name_plural': 'Corretores',
            },
        ),
    ]
