# Generated by Django 5.2 on 2025-04-20 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='telefone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="O telefone deve estar no formato '+999999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
