# Generated by Django 5.2 on 2025-04-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('vendas', models.ManyToManyField(blank=True, to='vendas.venda')),
            ],
        ),
    ]
